/**
 * srd-rules-engine — a 5th-edition (SRD 5.2.1) rules engine and character builder.
 *
 * Runs anywhere JavaScript does (Node, Deno, Bun, browsers, workers). The bundled SRD content is
 * in `srd-rules-engine/srd` (or per table, `srd-rules-engine/srd-5.2.1/*.json`, for `loadPack`);
 * loading YAML content from disk is in `srd-rules-engine/node`; the HTTP handler is in
 * `srd-rules-engine/http`.
 */

// Content
export {
  type Catalog,
  type CatalogOptions,
  CORE_TABLES,
  ContentError,
  type ContentPack,
  createCatalog,
  type Item,
  isLoaded,
  lookup,
  TABLE_NAMES,
  TABLE_SCHEMAS,
  type Table,
  type TableName,
  validateReferences,
} from "./content/catalog";
export {
  type LoadPackOptions,
  loadPack,
  type SplitManifest,
  splitPack,
} from "./content/split";
// The bundled SRD data is in `srd-rules-engine/srd`, not here: the engine stays small.
export { SRD_PACK_ID } from "./content/srd-id";
// Models
export {
  ABILITY_METHODS,
  type AbilityMap,
  type AbilityMethod,
  ALIGNMENT_NAMES,
  ALIGNMENTS,
  type Alignment,
  type CharacterBuild,
  CharacterBuildSchema,
  characterLevel,
  createBuild,
  type LevelUp,
  LevelUpSchema,
  parseBuild,
  updateBuild,
} from "./models/build";
export {
  ABILITY_FULL_NAMES,
  type AbilityFullName,
  AbilityFullNameSchema,
  type AbilityScores,
  AbilityScoresSchema,
  CHARACTER_CLASSES,
  type Character,
  type CharacterClass,
  CharacterSchema,
} from "./models/character";
export type {
  RollResult,
  SavingThrow,
} from "./models/combat";
export {
  ABILITIES,
  ABILITY_NAMES,
  type Ability,
  type AbilityBonus,
  AbilityBonusSchema,
  type AcCalculation,
  AcCalculationSchema,
  ADVANTAGE_TARGETS,
  type AdvantageGrant,
  AdvantageGrantSchema,
  type AdvantageTarget,
  type ArmorDef,
  ArmorSchema,
  type BackgroundDef,
  BackgroundSchema,
  CHOICE_KINDS,
  type ChoiceDef,
  ChoiceDefSchema,
  type ChoiceKind,
  type ChoiceOption,
  ChoiceOptionSchema,
  type ClassDef,
  ClassSchema,
  type ConditionDef,
  ConditionSchema,
  type CreationRules,
  CreationSchema,
  DAMAGE_TYPES,
  type DamageRider,
  DamageRiderSchema,
  type DamageType,
  DEFAULT_SOURCE,
  EFFECT_CONDITIONS,
  EFFECT_OPS,
  EFFECT_TARGETS,
  type Effect,
  type EffectCondition,
  type EffectOp,
  EffectSchema,
  type EffectTarget,
  FEATURE_RULES,
  type FeatDef,
  type FeatGrant,
  FeatGrantSchema,
  FeatSchema,
  type FeatureActionDef,
  FeatureActionSchema,
  type FeatureRule,
  type GearDef,
  GearSchema,
  type GrantedIdList,
  type Grants,
  GrantsSchema,
  type ItemGrant,
  ItemGrantSchema,
  isSkill,
  type LanguageDef,
  LanguageSchema,
  MAGIC_ITEM_CATEGORIES,
  type MagicItemDef,
  MagicItemSchema,
  type MasteryDef,
  MasterySchema,
  type MonsterAction,
  MonsterActionSchema,
  type MonsterDamage,
  type MonsterDef,
  MonsterSchema,
  type PointBuyRules,
  PointBuySchema,
  type Prerequisite,
  PrerequisiteSchema,
  type ResourceDef,
  ResourceSchema,
  SIZES,
  type Size,
  SKILL_ABILITY,
  SKILLS,
  type Skill,
  SPELL_AREAS,
  type SpeciesDef,
  SpeciesSchema,
  type SpellArea,
  SpellAreaSchema,
  type Spellcasting,
  SpellcastingSchema,
  type SpellDamage,
  SpellDamageSchema,
  type SpellDef,
  SpellDefSchema,
  type SpellMechanics,
  SpellMechanicsSchema,
  STEPS,
  type Step,
  type SubclassDef,
  SubclassSchema,
  skillName,
  type ToggleDef,
  type ToolDef,
  ToolSchema,
  type Trait,
  TraitSchema,
  type WeaponDef,
  WeaponSchema,
} from "./models/content";
export {
  type BattleMap,
  BattleMapSchema,
  ECONOMY,
  type EffectEnd,
  EffectEndSchema,
  type Encounter,
  type EncounterAction,
  EncounterActionSchema,
  type EncounterCombatant,
  EncounterCombatantSchema,
  type EncounterEffect,
  EncounterEffectSchema,
  EncounterSchema,
  type Help,
  HelpSchema,
  type MasteryMark,
  MasteryMarkSchema,
  type Pending,
  PendingSchema,
  POINT_KINDS,
  type PointKind,
  type PointOfInterest,
  PointOfInterestSchema,
  parseEncounter,
  type SpellMark,
  SpellMarkSchema,
  type Zone,
  ZoneSchema,
} from "./models/encounter";
export {
  type EncounterEvent,
  EncounterEventSchema,
  REFUSAL_CODES,
  type RefusalCode,
} from "./models/events";
export { type EncounterHistory, EncounterHistorySchema } from "./models/history";
export {
  type ActionCheck,
  ActionCheckSchema,
  type CombatantOptions,
  CombatantOptionsSchema,
  OPTION_COSTS,
  type OptionCost,
  type OptionEntry,
  OptionEntrySchema,
  type StrikeOption,
  StrikeOptionSchema,
  type TargetSpec,
  TargetSpecSchema,
} from "./models/options";
export {
  applyPatch,
  PATCH_OPS,
  type PackManifest,
  PackManifestSchema,
  type Patch,
  PatchError,
  type PatchOp,
  PatchSchema,
} from "./models/pack";
export {
  type AreaPreview,
  AreaPreviewSchema,
  type MovePreview,
  MovePreviewSchema,
  type Reachable,
  ReachableSchema,
} from "./models/previews";
export {
  type CharacterState,
  CharacterStateSchema,
  CURRENCIES,
  type Currency,
  type ItemInstance,
  ItemInstanceSchema,
  MAX_ATTUNED,
  type PlayAction,
  PlayActionSchema,
  parseState,
} from "./models/state";
export { DOCUMENT_VERSION, DocumentVersionSchema } from "./models/version";
// Rules
export {
  type AbilityRoll,
  backgroundBonusErrors,
  baseScoreErrors,
  finalScores,
  type PointBuyAbility,
  type PointBuyStatus,
  pointBuyCost,
  pointBuyStatus,
  rollAbilityScore,
  rollAbilityScores,
} from "./rules/ability-scores";
export {
  type AreaPlacement,
  areaSquares,
  distanceToPoint,
  type GridPoint,
  type GridSpace,
  inArea,
} from "./rules/areas";
export {
  type ActiveChoice,
  type ActiveSource,
  type ClassLevel,
  DEFAULT_SCORE,
  type OptionView,
  Resolution,
  resolve,
  type SwapFamily,
} from "./rules/build-resolution";
export {
  type Issue,
  issuesForLevel,
  issuesForStep,
  multiclassBlockers,
  reportErrors,
  SEVERITIES,
  type Severity,
  type ValidationReport,
  validateBuild,
} from "./rules/build-validation";
export {
  type CastOptions,
  cantripTier,
  castSpell,
  type SaveActionResult,
  type SpellAttackRoll,
  type SpellCastResult,
  type SpellFollowUpResult,
  type SpellTargetResult,
  useSaveAction,
} from "./rules/casting";
export { savingThrow } from "./rules/combat";
export {
  type AttackModeOptions,
  type AttackOptions,
  type AttackResult,
  attackMode,
  type CheckResult,
  type Combatant,
  type CombatantSpellcasting,
  type ConditionMode,
  type ConditionRolls,
  combatantFromMonster,
  combatantFromSnapshot,
  conditionRolls,
  type D20Roll,
  type Decide,
  type Decision,
  type LegendaryActionLine,
  type ModeReason,
  type MonsterSpellLine,
  type MonsterState,
  makeAttack,
  monsterSpells,
  NO_CONDITION_ROLLS,
  ROLL_MODES,
  type RollMode,
  resolveMode,
  rollAbilityCheck,
  rollD20,
  rollSavingThrow,
  type SaveActionLine,
  type SaveResult,
  type SpellDamageBonus,
} from "./rules/combatant";
export {
  COIN_VALUES,
  type Coin,
  coinsFor,
  formatCp,
  type Purse,
  pay,
  priceInCp,
  purseValue,
} from "./rules/currency";
export {
  adjustDamage,
  type DamageInstance,
  type DamagePart,
  type DamageResult,
  type Defenses,
  formatDamage,
  isBloodied,
  type RolledDamage,
  type RolledDamagePart,
  rollDamage,
  takeDamage,
  type Vitals,
} from "./rules/damage";
export {
  abilityModifier,
  type DiceExpression,
  formatDiceExpression,
  MAX_DICE,
  MAX_SIDES,
  parseDiceExpression,
  proficiencyBonus,
  roll,
} from "./rules/dice";
export {
  type CoverDegree,
  coverDegree,
  findPath,
  gridDistance,
  lineClear,
  type Occupant,
  obstacles,
  spaceForSize,
  stepBlocked,
  stepCost,
  straightPath,
  type Terrain,
  type Wall,
} from "./rules/grid";
export { attackOdds, averageDamage, failOdds } from "./rules/odds";
export {
  fixedRng,
  mathRng,
  type Rng,
  scriptedRng,
  seededRng,
} from "./rules/rng";
export {
  type AttackLine,
  type AttackRider,
  type CarriedItem,
  type ClassLine,
  type Contribution,
  computeSheet,
  type DerivedSheet,
  explainStat,
  type FeatureActionLine,
  type PlayContext,
  type ResourceLine,
  type SaveLine,
  type SkillLine,
  type SpellcastingLine,
  type SpellLine,
  type Stat,
  stat,
  type ToggleLine,
  type TraitLine,
  type UsesLine,
} from "./rules/sheet";
// Workflows
export * as builder from "./services/builder";
export {
  BuildError,
  type BuildResult,
  type Evaluation,
  evaluate,
  STEP_TITLES,
} from "./services/builder";
export {
  applyDamage,
  applyHealing,
  isAlive,
  passivePerception,
} from "./services/combat";
export {
  applyEncounterAction,
  type CharacterRef,
  type Cover,
  combatantPassivePerception,
  createEncounter,
  currentCombatant,
  type EncounterContext,
  EncounterError,
  type EncounterResult,
  encounterCombatant,
  type MapCover,
  mapCover,
  zoneSquares,
} from "./services/encounter";
export { encounterEvents } from "./services/events";
export {
  createHistory,
  recordAction,
  replayHistory,
  undoAction,
} from "./services/history";
export {
  checkAction,
  combatantOptions,
  type OptionsSettings,
} from "./services/options";
export {
  applyAction,
  combatantFromCharacter,
  computePlaySheet,
  createState,
  magicItemBases,
  PlayError,
  type PlaySheet,
  playBuild,
  reconcileState,
  startingEquipment,
  validateState,
} from "./services/play";
export {
  type AreaRequest,
  previewArea,
  previewMove,
  reachableSquares,
} from "./services/previews";
export { refusalCode } from "./services/refusals";
